# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fce1256d2db77b0f4f5ed0adb70dddf3fbb9c2aa7363ffc2ef37d0e76da28eb7690a852d0db596ebbc98a3c2c8a60fa51a9793dbcc051605f1ad0e0d8bb18436

test:
  secret_key_base: a2f8f05b07a08020202c66541fb4abdac8dc579911a6a9b9ea4bf6fb858241ba239c7f434834c28148c4e5eddafc685990569405f1a8d094e68d217e29fcd57d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
